[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "superpixel_graphs"  
version = "0.01"
authors = [
  { name="Julia Rodrigues", email="jprodrigues@inf.ufrgs.br" },
]

[tool.setuptools]
packages = ["superpixel_graphs"]